config/routes.rb
Rails.application.routes.draw do
 resources :documents, only: [:index, :new, :create, :destroy]
 root "documents#index"
end

app/models/document.rb
class Document < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def index
    @documents = Document.all.order("created_at DESC")
  end

  def new
    @document = Document.new
  end

  def create
    @document = Document.new(resume_params)

    if @document.save
      redirect_to documents_path, notice: "The document #{@document.name} has been uploaded."
    else
      render "new"
    end
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path, notice:  "The document #{@document.name} has been deleted."
  end

private
  def resume_params
    params.require(:document).permit(:name, :attachment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/create.html.haml
%h1 Documents#create
%p Find me in app/views/documents/create.html.erb

app/views/documents/destroy.html.haml
%h1 Documents#destroy
%p Find me in app/views/documents/destroy.html.erb

app/views/documents/index.html.haml
- if !flash[:notice].blank?
  .alert.alert-info
    = flash[:notice]
.wrapper_with_padding
  %h1 Sharebox
  %button= link_to "New Document", new_document_path
  %br/
  %br/
  %table.table.table-striped
    %thead
      %tr
        %th Name
        %th Download Link
        %th  
    %tbody
      - @documents.each do |document|
        %tr
          %td= "#{document.name} - #{time_ago_in_words(document.created_at)}"
          %td= link_to "Download Document", document.attachment_url
          %td= button_to "Delete",  document, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{document.name}?"

app/views/documents/new.html.haml
- if !@document.errors.empty?
  .alert.alert-error
    %ul
      - @document.errors.full_messages.each do |msg|
        %li= msg
.well
  = form_for @document, html: { multipart: true } do |f|
    = f.label :name
    = f.text_field :name
    = f.label :attachment
    = f.file_field :attachment
    = f.submit "Upload", class: "btn btn-primary"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Sharebox by Timekeeper
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container{:style => "padding-top:20px;"}
    %header
    .header_inner
      = link_to image_tag(''), root_path, id: "logo"
      %nav
      = yield